- name: Build the layout
  id: build-layout
  run: |
    # Set keyboard directory and make prefix based on firmware version
    if [ "${{ steps.download-layout-source.outputs.firmware_version }}" -ge 24 ]; then
      keyboard_directory="qmk_firmware/keyboards/zsa"
      make_prefix="zsa/"
    else
      keyboard_directory="qmk_firmware/keyboards"
      make_prefix=""
    fi

    # Copy layout files to the qmk folder
    rm -rf ${keyboard_directory}/${{ github.event.inputs.layout_geometry }}/keymaps/${{ github.event.inputs.layout_id }}
    mkdir -p ${keyboard_directory}/${{ github.event.inputs.layout_geometry }}/keymaps
    cp -r "./${{ github.event.inputs.layout_id }}/." \
      "${keyboard_directory}/${{ github.event.inputs.layout_geometry }}/keymaps/${{ github.event.inputs.layout_id }}/"

    # Build the layout
    docker run -v ./qmk_firmware:/root --rm qmk /bin/sh -c "
      set -x
      cd /root
      make ${make_prefix}${{ github.event.inputs.layout_geometry }}:${{ github.event.inputs.layout_id }}
    "

    # Figure out the output filename (this matches what the template uses)
    keyboard_target=\"$(basename \"${{ github.event.inputs.layout_geometry }}\")\"  # glow
    normalized_layout_geometry=\"ergodox_ez_${keyboard_target}\"
    layout_id=\"${{ github.event.inputs.layout_id }}\"
    built_file=\"${normalized_layout_geometry}_${layout_id}.hex\"

    echo \"built_layout_file=${built_file}\" >> \"$GITHUB_OUTPUT\"
    echo \"normalized_layout_geometry=${normalized_layout_geometry}\" >> \"$GITHUB_OUTPUT\"
